version: '3'
services:
  bot:
    build: .
    image: node:latest
    environment:
      NODE_ENV: 'production'
    volumes:
      - ./:/app
      - /app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: npm start